CPU_USAGE="/system/ui/providers/cpu_usage"
RAM_USAGE="/system/ui/providers/ram_usage"
GPU_USAGE="/system/ui/providers/gpu_usage"
NETWORK_IP="/system/ui/providers/network_ip"
CURRENT_FPS="/system/ui/providers/current_fps"
FRAME_TIME="/system/ui/providers/frame_time"
OPEN_FILES="/system/ui/scripts/open_files"
