set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR x86_64)
set(CMAKE_C_COMPILER "C:/git/csos/.tools/zig-x86_64-windows-0.16.0/zig.exe")
set(CMAKE_C_COMPILER_ARG1 "cc")
set(CMAKE_CXX_COMPILER "C:/git/csos/.tools/zig-x86_64-windows-0.16.0/zig.exe")
set(CMAKE_CXX_COMPILER_ARG1 "c++")
set(CMAKE_C_FLAGS_INIT "-target x86_64-linux-musl -fPIC -isystem C:/git/csos/zig-out/nix-sysroot-wsl/usr/include")
set(CMAKE_CXX_FLAGS_INIT "-target x86_64-linux-musl -fPIC -isystem C:/git/csos/zig-out/nix-sysroot-wsl/usr/include")
set(CMAKE_EXE_LINKER_FLAGS_INIT "-target x86_64-linux-musl")
set(CMAKE_SHARED_LINKER_FLAGS_INIT "-target x86_64-linux-musl")
set(CMAKE_FIND_ROOT_PATH "C:/git/csos/zig-out/nix-sysroot-wsl")
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
